In [6]:
from typing import Callable, Dict, List, Any
import pandas as pd
import numpy as np
import sqlite3
from concurrent.futures import ThreadPoolExecutor
from concurrent.futures._base import Future
import os
from string import ascii_uppercase
import pickle
import re
from sql_extract import extract_lines, lapply, clean_sql_file, ref_dict, id_lines

In [ ]:
def clean_sql_file(input_file_path: str, output_file_path: str):
    input_file = open(input_file_path, 'r') 
    output_file = open(output_file_path, "w")
    while True:
        try:
            line = input_file.readline()
            line = line.replace("\'","#!").replace("'", "\"")
            output_file.write(line)
            if line == '':
                break
        except:
            pass
    input_file.close() 
    output_file.close()

In [ ]:
ef clean_sql_file(input_file_path: str, output_file_path: str):
    input_file = open(input_file_path, 'r') 
    output_file = open(output_file_path, "w")
    while True:
        try:
            line = input_file.readline()
            
            output_file.write(line)
            if line == '':
                break
        except:
            pass
    input_file.close() 
    output_file.close()

In [37]:
"\"esf"

'"esf'

In [ ]:
data = pd.read_csv("Data/pairs_with_ratings.tsv", sep="\t").drop(['uid'], axis=1)
data

In [ ]:
print(data.isna().sum())
data.describe()

# SQL data
## Loading the data

In [2]:
with open('tables.pkl', 'rb') as f:
    tables = pickle.load(f) # deserialize using load()

## Cleaning the data

In [3]:
import sqlite3

# Step 1: Specify the path to the .sql file and the .db file
sql_file_path = "unfun_2023-02-02_test.sql"  # The .sql file containing SQL commands
db_file_path = 'new_test.db'  # The SQLite .db file to be created
nb_errors = 0
# Step 2: Connect to SQLite (it will create the .db file if it doesn't exist)
conn = sqlite3.connect(db_file_path)
cursor = conn.cursor()

# Step 3: Read the .sql file containing SQL commands
try:
    with open(sql_file_path, 'r') as sql_file:
        sql_script = sql_file.read()

    # Step 4: Execute the SQL script to create tables, insert data, etc.
    cursor.executescript(sql_script)
    print("SQL script executed successfully, and the SQLite database has been created.")
except FileNotFoundError as e:
    print(f"SQL file not found: {e}")
except sqlite3.Error as e:
    print(f"An error occurred while executing the SQL script: {e}")
    nb_errors+=1

finally:
    # Step 5: Commit changes and close the connection
    conn.commit()
    conn.close()
print("\n##############################################################\n")
print(f"Nb errors: {nb_errors}")


An error occurred while executing the SQL script: near "s": syntax error

##############################################################

Nb errors: 1


In [4]:
# Extracting all sql commands for relevent tables
commands = {
"create_original" : [],
"lines_original" : [],
"create_unfunned" : [],
"lines_unfunned" : [],
"create_ratings" : [],
"lines_ratings" : []
}
cursor_list = list(commands.keys())
cursor = len(cursor_list)
idx = 0
with open("unfun_2023-02-02_test.sql", 'r') as file:
    for _ in range(10):
        next(file)
        idx+=1
        print(idx,end="\r")
    for line in file:
        if line[:40].find("CREATE TABLE `headlines_original`") != -1:
            cursor = 0
        elif line[:40].find("INSERT INTO `headlines_original`") != -1:
            cursor = 1
        elif line[:40].find("CREATE TABLE `headlines_unfunned`") != -1:
            cursor = 2
        elif line[:40].find("INSERT INTO `headlines_unfunned`") != -1:
            cursor = 3
        elif line[:40].find("CREATE TABLE `ratings`") != -1:
            cursor = 4
        elif line[:40].find("INSERT INTO `ratings`") != -1:
            cursor = 5
        elif line == "\n":
            cursor = len(cursor_list)
        if cursor != len(cursor_list):
            commands[cursor_list[cursor]].append(line)
        idx+=1
        print(f"% {idx} | O: {len(commands["lines_original"])} | U: {len(commands["lines_unfunned"])} | R: {len(commands["lines_ratings"])}",end="\r")
print("\n")

% 144065 | O: 0 | U: 0 | R: 0



In [ ]:
tables["lines_original"]

In [14]:
np.array(list(tables.keys()))[["line" in string for string in list(tables.keys())]]

array(['lines_original', 'lines_unfunned', 'lines_ratings'], dtype='<U15')

In [ ]:
("".join(tables["lines_original"])).split(";")

In [16]:
("".join(tables["lines_original"])).split(");")[5].find("seriously")

779

In [22]:
("".join(tables["lines_original"])).split(");")[5][760:800]

" chief: al qaeda \\'seriously degraded\\' "

In [9]:
with open("new_tab_out.pkl", 'rb') as f:
    tables = pickle.load(f) # deserialize using load()
errors = {"lines_original": [],
          "lines_unfunned": [],
          "lines_ratings": []}
conn = sqlite3.connect("test.db")
cursor = conn.cursor()
nb_errors = 0
for table in np.array(list(tables.keys()))[["create" in string for string in list(tables.keys())]]:
    try:
        cursor.executescript(("".join(tables[table])).replace("ENGINE=InnoDB DEFAULT CHARSET=utf8", "").replace("\n",""))
        print("Script executed successfully.")
    except sqlite3.Error as e:
        print(f"An error occurred: {e}")
for lines in np.array(list(tables.keys()))[["line" in string for string in list(tables.keys())]]:
        inserts_comands = ("".join(tables[lines])).split(");")
        for insert, idx in zip(inserts_comands, range(len(inserts_comands))):
            try:
                cursor.executescript((insert+");").replace("\\'","''").replace('\\"', '"'))
                #print("Script executed successfully.")
            except sqlite3.Error as e:
                nb_errors+=1
                errors[lines].append([idx, re.search('"(.+?)"', str(e)).group(1)])
                print(f"An error occurred: during {lines} input, in INSERT: {idx}, {e}")
                #print((insert+";").replace("\\'","''").replace('\\"', '"'))
print("\n##############################################################\n")
print(f"Total number of unexecuted INSERT comands: {nb_errors}")
print(f"- original unexecuted INSERT: {len(errors["lines_original"])}")
print(f"- unfunned unexecuted INSERT: {len(errors["lines_unfunned"])}")
print(f"- ratings unexecuted INSERT: {len(errors["lines_ratings"])}")


An error occurred: table "headlines_original" already exists
An error occurred: table "headlines_unfunned" already exists
An error occurred: table "ratings" already exists
An error occurred: during lines_original input, in INSERT: 3, near "group": syntax error
An error occurred: during lines_original input, in INSERT: 4, near "brain": syntax error
An error occurred: during lines_original input, in INSERT: 5, near "ex": syntax error
An error occurred: during lines_original input, in INSERT: 6, near "cat": syntax error
An error occurred: during lines_original input, in INSERT: 7, near "should": syntax error
An error occurred: during lines_original input, in INSERT: 8, near "jami": syntax error
An error occurred: during lines_original input, in INSERT: 11, near "russian": syntax error
An error occurred: during lines_original input, in INSERT: 12, near "murray": syntax error
An error occurred: during lines_original input, in INSERT: 13, near "obama": syntax error
An error occurred: during 

In [17]:
idx = 0
tab_ref = "lines_original"
pos = ("".join(tables[tab_ref])).split(");")[errors[tab_ref][idx][0]].find(errors[tab_ref][idx][1])
("".join(tables[tab_ref])).split(");")[errors[tab_ref][idx][0]][pos-10:800]

' `headlines_original'

In [28]:
("".join(tables[tab_ref])).split(");")[0][pos-20:pos+20]

'NSERT INTO `headlines_original` (`id`, `'

In [ ]:
("".join(tables[tab_ref])).split(";")[0].split("\n")

In [5]:
SQL_con_2023 = sqlite3.connect("test.db")
cursor_2023 = SQL_con_2023.cursor()

In [21]:
get_list_tables = """SELECT name FROM sqlite_master WHERE type='table';"""
request = """ SELECT DISTINCT O.id, O.title, U.title, R.rating, U.date
              FROM headlines_original O, headlines_unfunned U, ratings R
              WHERE O.id = U.original_headline_id 
              and R.id = O.id
              and U.title is not null;

"""
cursor_2023.execute(request)
result = cursor_2023.fetchall()

In [20]:
len(result)

10452

In [88]:
("".join(tables["create_ratings"])).replace("ENGINE=InnoDB DEFAULT CHARSET=utf8", "").replace("\n","")

'CREATE TABLE `ratings` (  `id` int(11) NOT NULL,  `uid` varchar(95) NOT NULL,  `batch_id` varchar(32) NOT NULL,  `headline_id` int(11) NOT NULL,  `headline_type` varchar(32) NOT NULL,  `date` datetime NOT NULL,  `position` int(11) NOT NULL,  `rating` double DEFAULT NULL) ;'

In [17]:
import linecache 
particular_line = linecache.getline("unfun_2023-02-02.sql", 50809) 


In [20]:
particular_line.replace('\\"', '"')

'(9812, "internacional - cia "contrat?" a blackwater contra al-qaeda", "real", "bbc.co.uk", "http://bbc.co.uk/mundo/internacional/2009/08/090820_1200_eeuu_cia_blackwater_ms.shtml", "2009-08-20 15:01:00"),\n'

In [ ]:
replacement_dict = {"‘" : "'",
                    "’" : "'"}

In [9]:
starts = np.where(lines_types == ref_dict["Start_original"])[0]
ends = np.where(lines_types == ref_dict["Comand_end"])[0]

In [13]:
lines[70636]

np.str_('(24989),\n')

In [10]:
min(ends[ends > max(starts)])

np.int64(70363)

In [45]:
temp = ends[ends > min(starts)]
#temp = temp[temp < np.where(temp == min(ends[ends > max(starts)]))[0]]


In [44]:
min(ends[ends > max(starts)])

np.int64(70363)

In [ ]:
temp[:np.where(temp == min(ends[ends > max(starts)]))[0][0]+1]

In [38]:
temp

array([], dtype=int64)

In [ ]:
(ends > min(starts)) and (ends < max(starts))

In [129]:
lines[70185]

np.str_("(29266, 'American Airlines Drops Bereavement Fares', 'real', 'theonion.com', 'http://www.theonion.com/articles/american-airlines-drops-bereavement-fares,35438/', '2014-03-05 00:00:00');\n")

In [134]:
def extract_entires(lines_type_array: List[int], table_ref: str, ref_dict: Dict[str, int]) -> List[int]:
    nb_inserts = np.where(lines_type_array == ref_dict[table_ref])[0] # Get all the lines for the insert comand
    out = np.array([], dtype=int)
    for idx in range(len(nb_inserts)-1):
        start = nb_inserts[idx]
        end = nb_inserts[idx+1]
        print(f"start: {start}, end: {end}")
        entries = np.where(lines_type_array == ref_dict["Entry"])[0]
        out = np.append(out, entries[(entries > start) == (entries < end)])
        out = np.append(out, entries[end])
    return out
        

In [ ]:
test = extract_entires(lines_types, "Start_original", ref_dict)

In [136]:
lines[test]

array(["(9332, 'sunday feature: a brief history of cunning', 'real', 'bbc.co.uk', 'http://bbc.co.uk/go/rss/-/iplayer/episode/b00cx18z', '2008-08-13 00:06:38'),\n",
       "(9333, 'olympics - all programmes - page 1', 'real', 'bbc.co.uk', 'http://bbc.co.uk/go/rss/-/iplayer/categories/olympics', '2008-08-13 00:06:39'),\n",
       "(9334, 'house of saddam: episode 3', 'real', 'bbc.co.uk', 'http://bbc.co.uk/go/rss/-/iplayer/episode/b00d1y00', '2008-08-15 17:24:00'),\n",
       ...,
       "(29264, 'New Theme Park To Feature Model Of Noah’s Ark', 'real', 'theonion.com', 'http://www.theonion.com/articles/new-theme-park-to-feature-model-of-noahs-ark,35429/', '2014-03-03 00:00:00'),\n",
       "(29265, 'Pope Francis Drops F-Bomb During Vatican Blessing', 'real', 'theonion.com', 'http://www.theonion.com/articles/pope-francis-drops-fbomb-during-vatican-blessing,35437/', '2014-03-04 00:00:00'),\n",
       "(268, '504504090138', '8af62193b5bb39419aa2a5bf10591ba5', 22494, NULL, '2014-08-13 18:47:

In [106]:
test

array([50328, 50329, 50330, ..., 70179, 70180, 70916])

In [108]:
lines

array(['-- phpMyAdmin SQL Dump\n', '-- version 4.9.7\n',
       '-- https://www.phpmyadmin.net/\n', ..., '\n', '--\n', ''],
      dtype='<U652')

In [ ]:
nb_inserts = np.where(lines_types == ref_dict["Start_original"]) # Get all the lines for the insert comand
print(nb_inserts)

In [70]:
out = []
for idx in range(len(nb_inserts)-1):
    start = nb_inserts[idx]
    end = nb_inserts[idx+1]
    print(f"start: {start}, and: {end}")
    entries = np.where(lines_types == ref_dict["Entry"])[0]
    print(entries)
    out.extend(entries[(entries > start) == (entries < end)])

In [72]:
len(nb_inserts)

1

In [71]:
range(len(nb_inserts)-1)

range(0, 0)

In [64]:
entries = np.where(lines_types == ref_dict["Entry"])[0]
len(entries[(entries > 50327) == (entries < 50627)])

298

In [44]:
(entries > 50327 and entries < 50627

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [48]:
test = np.array([1,2,3,4,5,6,7,8,9,10])

In [60]:
(test > 1) == (test < 8)

array([False,  True,  True,  True,  True,  True,  True, False, False,
       False])

In [56]:
(test > 1 & test < 8).any()

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [28]:
np.where(lines == "ERROR")

(array([59738, 68013, 69084, 70150, 70756, 71489, 76271, 83666, 93156]),)

In [90]:
len("INSERT INTO `ratings`")

21

In [56]:
test= lapply(filter_line, lines)

In [36]:
print(out)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [ ]:
def filter_line(line: str):
    if line[0] not in ascii_uppercase + '(':
        return ""
    return line

test= apply_function_concurrently(lines[:5], filter_line)


In [16]:

lines = []
flag =False
with open('unfun_2023-02-02.txt') as file:

    for line in file:
        if not flag:
            if line.find("INSERT INTO `batches` (`id`, `uid`, `date`, `http_user_agent`, `ip_address`) VALUES"):
                flag = True
        if flag:
            try:
                lines.append(line)
            except:
                lines.append("ERROR")


UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1804: character maps to <undefined>